language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  app: spygi-cv
  on:
    repo: spygi/cv-app
  api_key:
    secure: llho5d29FcpLbPwocYv77tgbhRJ61yNe+N5sirgbEi91HGiKp+iALtuUx3zS8YgLgCKYejPmf+tsHDbjqMBbXaN4YszLWAYUGbdfraMIzS5Ao3+Gm459AIWUI5+cLCYzlXhmgyL1YyUbBgieBoHlBc2buisnWrsVjRVwJUp5u4qtrhwFq5OF+UCa2el4RTkJC1yslHdRXIOzXBCrehulUM4qBruQk9sYcTwVfvkDwo2BqM5sTdiOOXN1agjqg+W3EHgUvi5P3gVgKTD8QwF891KV9jWnj41v3LxSdxf4zm34awefsApjujfGiCev/IwuJO4+GLQ8x1wzWXii3zdkqSF/8MSa7FJgKlrhVAl7YIqWsJZ4a7QfXXvHkCLi9BvZhq+naiY/gTlv7aZTw6YvvlkbT0SU6l1nhUV8c1E0x0H/pH4fYhTeLipvgisQw2O0Nca23XFooDuwFB++f/Zp55t8gvwQyJrkt6psRIdgSdXgAQvMiZZ+lF9wRp6iBSpfgvRPZwZPfqHgHbiBxIjmTUoJ03NubZLIHxBtnguipxeUyeebqiJ7WaufVq47skcgkqdTUBdV48AaQu0DVQeOalgcpUkUuKgDBCDatyzaaSUpZt6guNfg1Xj1OOlY/mgZDQYAzFADbHnF2NUMNDybUX49Mk6aVbDyDrUZ1mOl+OM=
