language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: lNBOWoWgAYVG5CLKed8rzF0TQICawELvcMH0g04WXt0rJYzf+HoEJuGOjIIxIPtHyooMZlzzwbJ3nhN50AfYNDrAh8Gswm/zVZouHDgl9C839UiQm20bpzQf59qOF/rXXEVf4duvvW9E7T8m7h7nKa9NmyBaNLWiw1j2XXm7BruvMoo50BRWf23ybkZarE6237RpurMHPtlLalpxgjjyZWmnZWFdAW5M4aAsDMSlrQsaGW2b3gw8bI4WygYxHe+m79+ueBVEnLU2pDYfwbnOU2ku2e05agfgCjn+0bh0Lv6L6MpKoNgikLxa/79mO1d7RVQqleAAdgvqyt3m9su3l+43l8Jt5ohlMkaB61H5Naea0s+0INjxtkGn29CxBvEIDHi4hpq3ywLkhQwxbRpC1W9Dq3hlI0l1yj96aKzh5jko/vVcmn+b6Drs9+t+y4dWwAFpJdMgfDteECKP38U8oJ067HZ3rEjRSX3BybNst+nKWuBATUC1yPIGYknyvnOuXv+ZBfEBnbeS1HE+sj43VVNQSh7PoFiUdxutjNIWiRMQNlteIdHsk9i7OXshPjPpLeBzxzCpQkBWXERroXQUczbGc2q8BOSjnSL7vf6ieClyh7E0CAXAg9I8rBpvrXjKUR5ylyqu10bINXgq6zfJfL9WJUu6izSmez7PYWa7LpE=
  app: spygi-cv
  on:
    repo: spygi/cv-app